apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: travelo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/achraf-77733/travelo_k8s.git 
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: travelo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true