apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: travelo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travelo-frontend
  template:
    metadata:
      labels:
        app: travelo-frontend
    spec:
      containers:
      - name: frontend-container
        image: achrafb8h/travelo_frontend:1.1.1
        ports:
        - containerPort: 80